services:
  userservice:
    build: .
    container_name: userservice
    ports:
      - ${USERSERVICE_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${DBCORE_URL}
      SPRING_DATASOURCE_USERNAME: ${DBCORE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DBCORE_PASSWORD}
      SPRING_SERVER_PORT: ${USERSERVICE_PORT}
      SPRING_SERVER_ADDRESS: ${USERSERVICE_HOST}
    networks:
      - vizinhopet-net

networks:
  vizinhopet-net:
    external: true
